[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.1.0" }
remodel = { github = "rojo-rbx/remodel", version = "0.9.1" }
run-in-roblox = { github = "rojo-rbx/run-in-roblox", version = "0.3.0" }
stylua = { github = "JohnnyMorganz/stylua", version = "0.13.1" }
