[tools]
rojo = { source = "rojo-rbx/rojo", version = "=7.0.0-rc.1" }
remodel = { source = "rojo-rbx/remodel", version = "0.9.1" }
run-in-roblox = {source = "rojo-rbx/run-in-roblox", version = "0.3.0"}
