name: Deploy

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1.7.4

      - name: Compile game
        uses: make game

      - name: Deploy game
        run: yarn deploy --auth $ROBLOSECURITY
        env:
          ROBLOSECURITY: ${{ secrets.PUBLISHER_RBX_TOKEN }}
          
