# Taken from roblox-ts under the MIT license https://github.com/roblox-ts/roblox-ts/blob/master/.github/workflows/publish.yml
name: Publish

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  publish:
    if: github.repository == 'memolemo-studios/SoftwareTycoon' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.HUB_TOKEN }}

      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1.7.4

      - name: Compile game
        run: make game

      - name: Publish game
        run: |
          git rev-parse --abbrev-ref HEAD >> current_branch
          yarn deploy 
        env:
          REMODEL_AUTH: ${{ secrets.PUBLISHER_RBX_TOKEN }}
