# Taken from roblox-ts under the MIT license https://github.com/roblox-ts/roblox-ts/blob/master/.github/workflows/ci.yml
# Modified to deploy the game either the dev or the master branch

name: Publish

on:
  push:
    branches:
      - dev
      - master

jobs:
  publish:
    if: github.repository == 'memolemo-studios/SoftwareTycoon' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.HUB_TOKEN }}

      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1.7.4

      - name: Compile game
        run: make game

      - name: Publish game
        run: yarn deploy
        env:
          ROBLOSECURITY: ${{ secrets.PUBLISHER_RBX_TOKEN }}

      - name: Setup commitee user
        run: |
          git config user.name "Github Actions"
          git config user.email "noreply@github.com"

      - name: Commit changes with .mantle-state.yml file
        run: |
          git add .mantle-state.yml
          git commit -m "Mantle generated state file"
          git push -u origin HEAD
